namespace: dev-ep-bitswap-peer
image:
  version: 20230302.1601-dev
service:
  http:
    metricsMonitor:
      enable: false
    healthCheck:
      enable: "true"
      liveness:
        initialDelaySeconds: 15
        periodSeconds: 5
        timeoutSeconds: 1
        failureThreshold: 3
        successThreshold: 1
      readiness:
        initialDelaySeconds: 15
        periodSeconds: 12
        timeoutSeconds: 10
        failureThreshold: 10
        successThreshold: 1
  additionalResourceTags:
    Environment: dev
annotations:
  prometheus.io/path: metrics
  prometheus.io/port: "3001"
  prometheus.io/scrape: "true"
env:
  nodeEnv: dev
  peerIdS3Bucket: us-west-2-dev-ep-bitswap-config
  peerAnnounceAddr: /dns4/elastic-dev.dag.house/tcp/443/wss
  dynamodbBlocksTable: dev-ep-blocks
  dynamodbCarsTable: dev-ep-cars
  dynamodbBlocksTableV1: dev-ep-v1-blocks
  dynamodbCarsTableV1: dev-ep-v1-cars
  dynamodbLinkTableV1: dev-ep-v1-blocks-cars-position
  dynamodbConfigTable: dev-ep-bitswap-config
  logRequests: true
serviceAccountName: dev-ep-bitswap-irsa
resources:
  limits:
    cpu: 2
    memory: 6Gi
  requests:
    cpu: 1
    memory: 4Gi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 15
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
